### ISSUE TITLE
Withdrawing Stake

### ISSUE THREAD

**Issue by cryptothuggin** [celer-network/sgn-networks#8]
Hello, I have an issue withdrawing my stake. So i went ahead and click "initialize withdrawal" and right after that i went ahead and clicked "Confirm Withdraw" without waiting. Now i dont see anything in the contract reader. My etherscans shows every transaction went through, so nothing is stuck but now i cant see any funds at all. i just would like to know how i can go about getting my tokens back. Please help and thank you.

**Comment by xiaozhou** [comment]
Hi, please follow the [delegator instructions](undelegating stakes and pending withdrawals), wait for 100 ETH blocks after initializing, and then confirm the withdrawal. If your "initialize withdrawal" succeeded, you should be able to see `undelegating stakes` and `pending withdrawals` from the contract reader before submitting "confirm withdrawal".

**Comment by hhl42** [comment]
Hi, please follow the [delegator instructions](https://github.com/celer-network/sgn-networks/blob/master/docs/delegator.md#withdraw-stake), wait for 100 ETH blocks after initializing, and then confirm the withdrawal. If your "initialize withdrawal" succeeded, you should be able to see undelegating stakes and pending withdrawals from the contract reader before submitting "confirm withdrawal".
